version: "3"

services:
  database:
    image: mysql:8.0.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=geekshopping
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
